language: ruby
cache: bundler
sudo: false

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby

before_install:
  - gem install bundler

install:
  # Install gem dependencies
  - bundle

  # Install git-validation
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.10.2 bash)"
  - go get -u github.com/vbatts/git-validation

script:
  - rake
